### ISSUE TITLE
How to do time synchronization for multi LiDAR?

### ISSUE THREAD

**Issue by jibowen69** [gogojjh/M-LOAM#18]
Dear doctor jiao,
Thanks for your contribution to the community!
When I was trying to use multiple LiDARs, I found that LiDARs get the scan at different moments. So I would like to consult how to synchronize the clocks of multiple LiDARs through hardware. Thank you!

**Comment by gogojjh** [comment]
Two steps to support the time synchronization:
- Hardware-level: LiDARs are synchronized with the GPS timer. You may need to use a chip (such as an STM32) to publish PPS at a constant frequency so that each LiDAR scan starts at the same time. You can check with the Velodyne-16 manual for more details. If you meet some specific problems, you are recommended to ask Mr.Yilong Zhu (yzhubr@connect.ust.hk).
- Software-level: from my experiences, the synchronization issue for LiDAR is not serious. If you do not have the hardware, you can use the message filter to cope with LiDAR scans at different timestamps. This can reduce the time-offset effect. 
Example: https://github.com/gogojjh/M-LOAM/blob/a4cde14413b7d7a7173dafe467e27e91811e7f6f/estimator/src/rosNodeRHD.cpp#L207

Thanks.

**Comment by jibowen69** [comment]
I had understood , thanks for your help!
