### ISSUE TITLE
about the edge residual

### ISSUE THREAD

**Issue by nonlinear1** [gogojjh/M-LOAM#4]
in A. can-Based Motion Estimation of VI.INITIALIZATION in your paper:"Robust Odometry and Mapping for Multi-LiDARSystems with Online Extrinsic Calibration". I was confused with the edge residual. for  "where[w1,d1]and[w2,d2]are the coefficients ofΠ1andΠ2,w1coincides  with  the  projection  direction  fromLtop,  andΠ2is perpendicular toΠ1s.t.w2⊥w1, andw2⊥L. " in your paper, I think p in Π2, so rH(x,p,Π2) is equal to zero for ever! Could you give me some explantaiton about this part?
   Thank you very much!

**Comment by gogojjh** [comment]
Thanks for your question. 

The pipeline of the motion estimation should be: step1_each edge feature finds its correspondences -> step2_iteratively optimize the residual function with several iterations. At step 1, rH(x, p, Π2) is zero; but during the optimization, since **x** is changing, rH(x, p, Π2) is not always zero. This term can constrain that the optimization direction goes into the **right** direction.

But we find that in many experiments, the usage of rH(x, p, Π2) only has a little help to the precision, but induces a higher computation cost. Therefore, the currently released code does not use rH(x, p, Π2) anymore. The new residuals are detailed in: https://ram-lab.com/file/site/m-loam/m-loam-gf/supp.pdf

**Comment by nonlinear1** [comment]
Thanks a lot! I understand totally!
